# Upstream для main API с sticky sessions
upstream main_backend {
    hash $cookie_jsessionid consistent;  # Хэш по cookie сессии
    server ${MAIN_BACKEND_SERVER};
    keepalive 32;
}

# Upstream для API Product с sticky sessions  
upstream api_product_backend {
    hash $cookie_jsessionid consistent;  # Хэш по cookie сессии
    server ${API_PRODUCT_SERVER};
    keepalive 32;
}

upstream api_product_ticketing {
    hash $cookie_jsessionid consistent;  # Хэш по cookie сессии
    server ${API_TICKETING_SERVER};
    keepalive 32;
}

server {
    listen      80;
    listen  [::]:80;
    server_name  localhost;

    root   /var/www/html/one-sim-portal/;
    index  index.html index.htm;
    
    # API Product service с sticky sessions
    location /api-product/ {
        proxy_pass http://api_product_backend/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api-ticketing/ {
        proxy_pass http://api_product_ticketing/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Main API calls с sticky sessions
    location ~ ^/api/(.*)$ {
        proxy_pass http://main_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    }

    # Auth calls с sticky sessions
    location ~ ^/auth/(.*)$ {
        proxy_pass http://main_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Static files and SPA fallback
    location / {
        try_files $uri $uri/ /index.html;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}



